@DutyAPI_HostAddress = http://localhost:5163

### Create a new Duty
POST http://localhost:5163/duty
Content-Type: application/json

{
  "id": "b3cbe0a4-8b5a-4f36-a0c9-1224d5c1db99",
  "name": "Take a picture of the cash desk.",
  "roleId": "bf2c1234-5678-90ab-cdef-1234567890ab"
}

### Get all Duties
GET http://localhost:5163/duty

### Get Duties by Role
GET http://localhost:5163/duty/role/bf2c1234-5678-90ab-cdef-1234567890ab

### Get Duty by ID
GET http://localhost:5163/duty/id/b3cbe0a4-8b5a-4f36-a0c9-1224d5c1db99

### Update a Duty
PUT http://localhost:5163/duty/id/b3cbe0a4-8b5a-4f36-a0c9-1224d5c1db99
Content-Type: application/json

{
  "id": "b3cbe0a4-8b5a-4f36-a0c9-1224d5c1db99",
  "name": "Take 2 pictures of the cash desk",
  "roleId": "bf2c1234-5678-90ab-cdef-1234567890ab"
}

### Delete a Duty
DELETE http://localhost:5163/duty/id/b3cbe0a4-8b5a-4f36-a0c9-1224d5c1db99

